_answers_file: .bhklab-template-builder-answers.yml

_exclude:
  - includes

_templates_suffix: .jinja

_subdirectory: TEMPLATE

_message_before_copy: |
  Thanks for generating a project using our template.

  You'll be asked a series of questions whose answers will be used to
  generate a tailored project for you.

_tasks:
  # {{ pixi_install_envs }} is a list of strings
  - echo "Initializing a git repository..."
  - git init
  - pixi install --all
  - mkdir -p {config,metadata,resources,logs,sandbox}
  - mkdir -p workflow/{notebooks,scripts}
  - mkdir -p data/{rawdata,procdata,results}
  - >-
    {% if is_snakemake %}
    mkdir -p workflow/{rules,envs,config,profiles,reports} && touch workflow/Snakefile
    {% endif %}
  - git add .
  - git commit -m "first commit"


_message_after_copy: |
  Your project "{{ project_name }}" has been created successfully!

  Next steps:

  1. Change directory to the project root:

     $ cd {{ _copier_conf.dst_path }}

  2. Enter the `dev` environment:

     $ pixi shell -e dev
