[workspace]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
name = "bhklab_test_template"
platforms = ["osx-arm64"]
version = "0.1.0"
description = "A simple template for BHKLAB projects using pixi"
license = "MIT"

[tasks]

[environments]
quality = { features = ["lint"] }

[dependencies]
copier = ">=9.2.0,<9.3"

[feature.lint.dependencies]
pre-commit-hooks = ">=4.6.0,<4.7"
pre-commit = ">=3.7.1,<3.8"
yamllint = ">=1.35.1,<1.36"

[feature.lint.tasks]
_pre-commit_setup = { cmd = "pre-commit install" }
pre-commit_run = { cmd = "pre-commit run --all-files", depends-on = [
    "_pre-commit_setup"
], description = "Run basic pre-commit quality checks" }
